title: Vo Anh Kiet
remote_theme: ToiLaKiet/minimal
description: _Taken since I was on 12th grade_
logo: assests/IMG_3951.JPG
params:
  favicon: assests/favicon.jpg
google_analytics: 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
